ewm: stat-service & docker
MayFoxes/java-explore-with-me pull request #1
Opened 2024-06-20 10:05 UTC by MayFoxes

Реализация сервиса статистики.

2024-06-21 17:37 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть одно небольшое замечание, которое стоит исправить!

Желаю удачи!

2024-06-21 17:37 UTC, LexLippi commented on stat-service/stat-server/src/main/java/ru/practicum/ewm/repository/StatsRepositoryImpl.java
> +        String query = unique ?
Лучше использовать `StringBuilder`

2024-06-21 19:38 UTC, MayFoxes commented
Исправил замечания

2024-06-22 15:57 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в остальных частях дипломного проекта!

2024-06-23 09:02 UTC, merged