Main svc
MayFoxes/java-explore-with-me pull request #2
Opened 2024-07-03 22:16 UTC by MayFoxes

2024-07-08 09:44 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        categoryRepository.delete(checkExist(id));
Зачем второй раз вызывать `checkExist`, если уже делали это для данного идентификатора?

2024-07-08 09:44 UTC, LexLippi commented on stat-service/stat-server/src/main/resources/schema.sql
> +    CREATED      TIMESTAMP WITHOUT TIME ZONE,
Может быть `null`?

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/request/controller/RequestPrivateController.java
> +    public ParticipationRequestDto addRequest(@PathVariable @Min(0) Long userId,
Вообще обычно идентификаторы все-таки начинаются с 1

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        }
можно использовать тернарный оператор, тогда не придется объявлять переменную без инициализации

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/events/controller/priv/EventPrivateController.java
> +                                           @PathVariable @Min(0) Long eventId,
Про идентификаторы уже писал

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/events/model/enums/EventAdminState.java
> +    public static Optional<EventAdminState> from(String stringState) {
Можно переписать с использованием Stream API:

```java
return Arrays.stream(values())
    .filter(state -> state.name().equalsIgnoreCase(stringState))
    .findFirst();
```

2024-07-08 09:44 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewm/events/model/enums/EventUserState.java
> +    public static Optional<EventUserState> from(String stringState) {
Про это уже писал

2024-07-08 10:49 UTC, MayFoxes commented
Исправил замечания

2024-07-09 07:45 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с заключительным этапом диплома!

2024-07-09 09:43 UTC, merged