ewm-feature: add comments and postman tests for them
MayFoxes/java-explore-with-me pull request #3
Opened 2024-07-09 22:07 UTC by MayFoxes

Добавлена реализация комментариев к событиям

2024-07-10 09:53 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть одно небольшое замечание, которое необходимо исправить!

Желаю удачи!

2024-07-10 09:53 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +    EDITED          BOOLEAN,
Всегда советую использовать булево поле, как истинно булево, запрезая ему быть `null`, потому что иначе это уже три допустимых значения и логика усложняется :)

2024-07-10 16:28 UTC, MayFoxes commented
Убрал обертку у болевого значения в таблицах в бд и подкорректировал методы под изменения.

2024-07-11 13:33 UTC, LexLippi commented
Привет!

Отличная работа!

Поздравляю тебе с окончанием курса Java-разработчик! Надеюсь наш курс был полезным для тебя, а мои ревью были для тебя полезными и еще помогут тебе в будущем!

Желаю удачи в дальнейшем пути!

2024-08-10 12:48 UTC, merged